config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"
  resources :users
  resources :workouts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :workouts, dependent: :destroy
end

app/models/workout.rb
class Workout < ApplicationRecord
    belongs_to :user

    validates :exercise, presence: true, length: { maximum: 50 }
    validates :weight, presence: true, numericality: { greater_than_or_equal_to: 0 }
    validates :reps, presence: true, numericality: { only_integer: true, greater_than: 0 }
    validates :workout_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, notice: "User was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.expect(user: [ :name, :email ])
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_workout, only: %i[ show edit update destroy ]

  # GET /workouts
  def index
    @workouts = current_user ? current_user.workouts : Workout.none
  end

  # GET /workouts/1
  def show
  end

  # GET /workouts/new
  def new
    @workout = current_user.workouts.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  def create
    @workout = current_user.workouts.new(workout_params)

    if @workout.save
      redirect_to @workout, notice: "Workout was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /workouts/1
  def update
    if @workout.update(workout_params)
      redirect_to @workout, notice: "Workout was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /workouts/1
  def destroy
    @workout.destroy
    redirect_to workouts_path, notice: "Workout was successfully deleted."
  end

  private

    # Loads workout ONLY belonging to current user
    def set_workout
      @workout = current_user.workouts.find(params[:id])
    end

    def workout_params
      params.require(:workout).permit(:exercise, :weight, :reps, :workout_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <div class="navbar-left">
    <%= link_to root_path do %>
      <%= image_tag "dumbbell.png", class: "navbar-logo", alt: "Home" %>
    <% end %>
  </div>

  <div class="navbar-links">
    <%= link_to "Home", root_path, class: "nav-link" %>
    <%= link_to "Workouts", workouts_path, class: "nav-link" %>


    <% if user_signed_in? %>
      <%= link_to "Sign Out",
                  destroy_user_session_path,
                  method: :delete,
                  data: { turbo_method: :delete },
                  class: "nav-link" %>
    <% else %>
      <%= link_to "Sign In",
                  new_user_session_path,
                  class: "nav-link" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Gym Tracker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Gym Tracker">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>


    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

 
  <body class="bg-light">

    <%= render "layouts/navbar" %>

    <div class="main-content">
      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>

      <% if alert %>
        <div class="alert alert-danger"><%= alert %></div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Gym Tracker</h1>
<p>Track all your workouts</p>
<div style="margin-top:20px;">
  <%= link_to "View Workouts", workouts_path, class: "btn btn-primary" %><br><br>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <div>
    <strong>Name:</strong>
    <%= user.name %>
  </div>

  <div>
    <strong>Email:</strong>
    <%= user.email %>
  </div>

</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path, class: "button" %>

app/views/users/new.html.erb
<% content_for :title, "New user" %>

<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

app/views/workouts/_form.html.erb
<%= form_with(model: workout) do |form| %>
  <% if workout.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
        <% workout.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :exercise, style: "display: block" %>
    <%= form.text_field :exercise %>
  </div>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.number_field :weight %>
  </div>

  <div>
    <%= form.label :reps, style: "display: block" %>
    <%= form.number_field :reps %>
  </div>

  <div>
    <%= form.label :workout_date, style: "display: block" %>
    <%= form.date_field :workout_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/workouts/_workout.html.erb
<div id="<%= dom_id workout %>">
  <div>
    <strong>Exercise:</strong>
    <%= workout.exercise %>
  </div>

  <div>
    <strong>Weight:</strong>
    <%= workout.weight %>
  </div>

  <div>
    <strong>Reps:</strong>
    <%= workout.reps %>
  </div>

  <div>
    <strong>Workout date:</strong>
    <%= workout.workout_date %>
  </div>

</div>

app/views/workouts/edit.html.erb
<% content_for :title, "Editing workout" %>

<h1>Editing workout</h1>

<%= render "form", workout: @workout %>

<br>

<div>
  <%= link_to "Show this workout", @workout %> |
  <%= link_to "Back to workouts", workouts_path %>
</div>

app/views/workouts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Workouts" %>

<h1>Workouts</h1>

<div id="workouts" class="workout-section">
  <% @workouts.each do |workout| %>
    <div class="workout-card">
     <%= render workout %>
     <p>
        <%= link_to "Show this workout", workout, class:"workout-link" %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to "New workout", new_workout_path, class:"button" %>

app/views/workouts/new.html.erb
<% content_for :title, "New workout" %>

<h1>New workout</h1>

<%= render "form", workout: @workout %>

<br>

<div>
  <%= link_to "Back to workouts", workouts_path %>
</div>

app/views/workouts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @workout %>

<div>
  <%= link_to "Edit this workout", edit_workout_path(@workout) %> |
  <%= link_to "Back to workouts", workouts_path %>

  <%= button_to "Destroy this workout", @workout, method: :delete %>
</div>